# https://stackoverflow.com/a/43677463

version: "2"
services:
  rabbit_node_1:
    environment:
      - RABBITMQ_ERLANG_COOKIE='secret_cookie'
    networks:
      - back
    hostname: rabbit_node_1
    image: "rabbitmq:3-management"
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - rabbit1:/var/lib/rabbitmq
    command: bash -c "rabbitmq-server"
volumes:
  rabbit1:
    driver: local
networks:
  back:
