// <auto-generated />
using System;
using GestaoReservasQuery.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GestaoReservasQuery.Migrations
{
    [DbContext(typeof(GestaoReservasQueryContext))]
    [Migration("20200616183450_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5");

            modelBuilder.Entity("GestaoReservasQuery.Model.Obra", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("estado")
                        .HasColumnType("INTEGER");

                    b.Property<string>("polo")
                        .HasColumnType("TEXT");

                    b.Property<string>("titulo")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Obra");
                });

            modelBuilder.Entity("GestaoReservasQuery.Model.Reserva", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("dataFim")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("dataInicio")
                        .HasColumnType("TEXT");

                    b.Property<string>("estado")
                        .HasColumnType("TEXT");

                    b.Property<long?>("obraId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("utente")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("obraId");

                    b.ToTable("Reservas");
                });

            modelBuilder.Entity("GestaoReservasQuery.Model.Reserva", b =>
                {
                    b.HasOne("GestaoReservasQuery.Model.Obra", "obra")
                        .WithMany()
                        .HasForeignKey("obraId");
                });
#pragma warning restore 612, 618
        }
    }
}
